<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MGD_WordPress_MCP_Updater {
 private static $instance=null; private $repo=MGD_WPMCP_GITHUB_REPO;
 public static function instance(){if(null===self::$instance){self::$instance=new self();}return self::$instance;}
 private function __construct(){add_filter('pre_set_site_transient_update_plugins',array($this,'inject_update'));add_filter('update_plugins_github.com',array($this,'update_uri_response'),10,4);add_filter('plugins_api',array($this,'plugin_info'),20,3);add_action('upgrader_process_complete',array($this,'clear_cache'),10,2);}
 private function cache_key(){return 'mgd_wpmcp_release_'.md5($this->repo);}
 private function normalize_version($tag){if(!is_string($tag)){return '';} $v=ltrim(trim($tag),'vV');return preg_match('/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/',$v)?$v:'';}
 private function should_refresh_cached_release($cached){if(!is_array($cached)||empty($cached['tag_name'])){return true;}$v=$this->normalize_version($cached['tag_name']);return ''===$v||!version_compare($v,MGD_WPMCP_VERSION,'>');}
 private function release(){if(!MGD_WordPress_MCP::setting('github_updates',true)){return array();}$cached=get_site_transient($this->cache_key());if(is_array($cached)&&!$this->should_refresh_cached_release($cached)){return $cached;}$r=wp_safe_remote_get('https://api.github.com/repos/'.$this->repo.'/releases/latest',array('timeout'=>10,'headers'=>array('Accept'=>'application/vnd.github+json','User-Agent'=>'MGD-WordPress-MCP/'.MGD_WPMCP_VERSION)));if(is_wp_error($r)||200!==wp_remote_retrieve_response_code($r)){return array();}$d=json_decode(wp_remote_retrieve_body($r),true);if(!is_array($d)||empty($d['tag_name'])||''===$this->normalize_version($d['tag_name'])||''===$this->package_url($d)){return array();}set_site_transient($this->cache_key(),$d,6*HOUR_IN_SECONDS);return $d;}
 private function package_url($release){if(empty($release['assets'])||!is_array($release['assets'])){return '';}foreach($release['assets'] as $a){if(!isset($a['name'],$a['browser_download_url'])||'mgd-wordpress-mcp.zip'!==$a['name']){continue;}$url=esc_url_raw($a['browser_download_url']);$p=wp_parse_url($url);if(!is_array($p)||'https'!==($p['scheme']??'')||'github.com'!==($p['host']??'')){return '';}if(0!==strpos($p['path']??'','/MichaelGahnDESIGN/MGD_WordPress-MCP/releases/download/')){return '';}return $url;}return '';}
 private function branding(){return array('icons'=>array('1x'=>MGD_WPMCP_URL.'assets/branding/robot-icon.svg','2x'=>MGD_WPMCP_URL.'assets/branding/robot-icon.svg'),'banners'=>array('low'=>MGD_WPMCP_URL.'assets/branding/plugin-banner-772x250.jpg','high'=>MGD_WPMCP_URL.'assets/branding/plugin-banner-1544x500.jpg'));}
 private function build_update($release){if(empty($release['tag_name'])){return null;}$v=$this->normalize_version($release['tag_name']);$pkg=$this->package_url($release);if(''===$v||''===$pkg||!version_compare($v,MGD_WPMCP_VERSION,'>')){return null;}$b=$this->branding();return(object)array('id'=>'https://github.com/'.$this->repo,'slug'=>'mgd-wordpress-mcp','plugin'=>MGD_WPMCP_BASENAME,'new_version'=>$v,'version'=>$v,'url'=>'https://github.com/'.$this->repo,'package'=>$pkg,'tested'=>'7.1','requires'=>'6.9','requires_php'=>'7.4','icons'=>$b['icons'],'banners'=>$b['banners']);}
 public function inject_update($t){if(!is_object($t)||empty($t->checked)){return $t;}$u=$this->build_update($this->release());if(null===$u){return $t;}if(!isset($t->response)||!is_array($t->response)){$t->response=array();}$t->response[MGD_WPMCP_BASENAME]=$u;return $t;}
 public function update_uri_response($update,$plugin_data,$plugin_file,$locales){if(MGD_WPMCP_BASENAME!==$plugin_file){return $update;}$u=$this->build_update($this->release());if(null===$u){return false;}return array('id'=>$u->id,'slug'=>$u->slug,'version'=>$u->new_version,'new_version'=>$u->new_version,'url'=>$u->url,'package'=>$u->package,'tested'=>$u->tested,'requires'=>$u->requires,'requires_php'=>$u->requires_php,'icons'=>$u->icons,'banners'=>$u->banners);}
 private function sections($release){
  $description='<h2>WordPress trifft KI – sicher, kontrolliert und flexibel.</h2><p><strong>MGD WordPress MCP</strong> verbindet deine WordPress-Website über das Model Context Protocol mit kompatiblen KI-Agenten wie Claude Code, Codex und anderen MCP-Clients. Statt eines unbeschränkten Fernzugriffs stellt das Plugin klar definierte Werkzeuge bereit, die sich an WordPress-Benutzerrechten und zusätzlichen Freigaben orientieren.</p>';
  $description.='<h3>Das kann MGD WordPress MCP</h3><table class="widefat striped"><tbody><tr><td><strong>🔗 KI-Agenten verbinden</strong><br>Ein eigener MCP-Endpunkt verbindet kompatible Clients kontrolliert mit WordPress.</td><td><strong>🛡 Sicher & kontrollierbar</strong><br>Schreiben, Divi, Medienimporte und Wartung besitzen getrennte Freigaben.</td></tr><tr><td><strong>✎ Inhalte & Medien</strong><br>Beiträge und Seiten lesen, Entwürfe erstellen, Inhalte bearbeiten und Medien verwalten.</td><td><strong>◇ Divi 5 & Builder</strong><br>Divi 5, Elementor, Gutenberg, Bricks und Beaver Builder werden berücksichtigt.</td></tr><tr><td><strong>⌁ SEO & Formulare</strong><br>Integrationen für Rank Math, Yoast und WPForms sind vorgesehen.</td><td><strong>↻ Backups & Updates</strong><br>UpdraftPlus und kontrollierte Einzelupdates können über Freigaben verwendet werden.</td></tr></tbody></table>';
  $description.='<h3>Privacy by Default</h3><p>Keine Google Fonts, keine externen Icon- oder JavaScript-CDNs, keine Telemetrie und kein Tracking. Die Oberfläche verwendet lokale Plugin-Assets und den WordPress-/System-Fontstack. Die optionale GitHub-Abfrage dient ausschließlich der Versionsprüfung.</p>';
  $description.='<h3>Für Agenten entwickelt, aber der Mensch behält die Kontrolle</h3><p>Schreibfunktionen sind standardmäßig deaktiviert. WordPress-Capabilities bleiben maßgeblich. Sensiblere Aktionen erhalten zusätzliche Freigaben und können im lokalen Audit-Log nachvollzogen werden.</p>';
  $description.='<h3>Projekt & Dokumentation</h3><p><a href="https://github.com/MichaelGahnDESIGN/MGD_WordPress-MCP" target="_blank" rel="noopener noreferrer">GitHub Repository</a> &nbsp;·&nbsp; <a href="https://github.com/MichaelGahnDESIGN/MGD_WordPress-MCP/tree/main/wiki" target="_blank" rel="noopener noreferrer">Wiki & Dokumentation</a> &nbsp;·&nbsp; <a href="https://Michael-Gahn.de" target="_blank" rel="noopener noreferrer">Michael Gahn DESIGN</a></p>';
  $description.='<hr><h3>Impressum gemäß § 5 DDG</h3><p><strong>Michael Gahn DESIGN</strong><br>Inhaber: Michael Gahn<br>Dr.-Theodor-Brugsch-Str. 12<br>08529 Plauen<br>Deutschland</p><p>Telefon: +49 (0) 151 59156639<br>E-Mail: Anfrage@Michael-Gahn.de<br>Umsatzsteuer-Identifikationsnummer: <strong>DE288143343</strong><br>Steuernummer: <strong>223/222/02451</strong><br>Lizenz: GPL-2.0-or-later</p>';
  return array(
   'description'=>$description,
   'installation'=>'<h2>In wenigen Schritten startklar</h2><ol><li><strong>Plugin installieren:</strong> <code>mgd-wordpress-mcp.zip</code> in WordPress installieren und aktivieren.</li><li><strong>Assistent öffnen:</strong> Builder und Umgebung automatisch erkennen lassen.</li><li><strong>MCP Adapter prüfen:</strong> Der offizielle WordPress MCP Adapter muss aktiv sein.</li><li><strong>Eigenes Application Password:</strong> Für den MCP-Client ein separates Kennwort im WordPress-Benutzerprofil erstellen.</li><li><strong>Minimal freigeben:</strong> Nur die wirklich benötigten Schreib-, Divi-, Medien- oder Wartungsfunktionen aktivieren.</li></ol><h3>MCP-Endpunkt</h3><p><code>https://DEINE-DOMAIN.TLD/wp-json/mgd-wordpress-mcp/v1/mcp</code></p><h3>Sicherheitsregel</h3><p>Application Passwords und andere Secrets gehören ausschließlich in den Secret-Speicher des MCP-Clients. Nicht in Chats, Dokumentationen, GitHub oder Screenshots speichern.</p>',
   'faq'=>'<h2>Häufige Fragen</h2><h3>Kann ein verbundener Agent automatisch alles in WordPress ändern?</h3><p>Nein. Lesen und Schreiben werden durch WordPress-Rechte und zusätzliche MGD-Freigaben begrenzt. Schreib- und Wartungsfunktionen starten deaktiviert.</p><h3>Funktioniert das Plugin mit Divi 5?</h3><p>Ja. Divi 5 wird erkannt und besitzt eine eigene kontrollierte Integration. Ergänzend gibt es den kostenlosen MGD Divi 5 Dev Skill für Agenten.</p><h3>Kann WordPress MGD WordPress MCP automatisch aktualisieren?</h3><p>Ja. Die GitHub-basierte Updatekette wurde real End-to-End getestet. Neue Releases erscheinen in der normalen WordPress-Updateoberfläche.</p><h3>Werden externe Fonts, Tracker oder Analyse-Skripte geladen?</h3><p>Nein. Die Admin-Oberfläche arbeitet Privacy by Default mit lokalen Assets.</p><h3>Ist das Plugin Open Source?</h3><p>Ja. MGD WordPress MCP steht unter GPL-2.0-or-later und wird öffentlich auf GitHub entwickelt.</p>',
   'changelog'=>!empty($release['body'])?wp_kses_post(nl2br($release['body'])):'<p>Die vollständige Versionshistorie findest du in den GitHub Releases.</p>'
  );
 }
 public function plugin_info($result,$action,$args){if('plugin_information'!==$action||!is_object($args)||'mgd-wordpress-mcp'!==($args->slug??'')){return $result;}$r=$this->release();$v=!empty($r['tag_name'])?$this->normalize_version($r['tag_name']):MGD_WPMCP_VERSION;$b=$this->branding();return(object)array('name'=>'MGD WordPress MCP','slug'=>'mgd-wordpress-mcp','version'=>$v?:MGD_WPMCP_VERSION,'author'=>'<a href="https://Michael-Gahn.de">Michael Gahn DESIGN</a>','author_profile'=>'https://Michael-Gahn.de','homepage'=>'https://Michael-Gahn.de','requires'=>'6.9','tested'=>'7.1','requires_php'=>'7.4','last_updated'=>'2026-09-15','active_installs'=>1,'download_link'=>$this->package_url($r),'icons'=>$b['icons'],'banners'=>$b['banners'],'sections'=>$this->sections($r),'external'=>true);}
 public function clear_cache($upgrader,$options){if(isset($options['type'])&&'plugin'===$options['type']){delete_site_transient($this->cache_key());}}
}
