<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class MGD_WordPress_MCP_Wizard {
 const OPTION_WIZARD='mgd_wordpress_mcp_wizard'; private static $instance=null;
 public static function instance(){if(null===self::$instance){self::$instance=new self();}return self::$instance;}
 private function __construct(){add_action('admin_init',array($this,'redirect_after_activation'));add_action('admin_post_mgd_wpmcp_wizard_save',array($this,'save'));add_action('admin_post_mgd_wpmcp_wizard_profile',array($this,'save_profile'));add_action('admin_post_mgd_wpmcp_wizard_finish',array($this,'finish'));}
 public static function activate(){if(false===get_option(self::OPTION_WIZARD,false)){add_option(self::OPTION_WIZARD,array('completed'=>false,'builder'=>'','other_builder'=>'','divi_skill'=>'ask'),'',false);}set_transient('mgd_wpmcp_wizard_redirect',1,60);}
 public function redirect_after_activation(){if(!get_transient('mgd_wpmcp_wizard_redirect')||!current_user_can('manage_options'))return;delete_transient('mgd_wpmcp_wizard_redirect');if(wp_doing_ajax()||isset($_GET['activate-multi']))return;wp_safe_redirect(admin_url('tools.php?page=mgd-wordpress-mcp&tab=wizard'));exit;}
 public static function data(){$d=get_option(self::OPTION_WIZARD,array());return wp_parse_args(is_array($d)?$d:array(),array('completed'=>false,'builder'=>'','other_builder'=>'','divi_skill'=>'ask'));}
 public function save(){if(!current_user_can('manage_options'))wp_die(esc_html__('Keine Berechtigung.','mgd-wordpress-mcp'));check_admin_referer('mgd_wpmcp_wizard_save');$allowed=array('divi','elementor','gutenberg','bricks','beaver-builder','other');$builder=isset($_POST['builder'])?sanitize_key(wp_unslash($_POST['builder'])):'';if(!in_array($builder,$allowed,true))$builder='';update_option(self::OPTION_WIZARD,array('completed'=>false,'builder'=>$builder,'other_builder'=>isset($_POST['other_builder'])?sanitize_text_field(wp_unslash($_POST['other_builder'])):'','divi_skill'=>('divi'===$builder&&!empty($_POST['divi_skill']))?'recommended':'not-selected'),false);wp_safe_redirect(admin_url('tools.php?page=mgd-wordpress-mcp&tab=wizard&saved=1'));exit;}
 public function save_profile(){if(!current_user_can('manage_options'))wp_die(esc_html__('Keine Berechtigung.','mgd-wordpress-mcp'));check_admin_referer('mgd_wpmcp_wizard_profile');$profile=sanitize_key(wp_unslash($_POST['profile']??''));if(!in_array($profile,array('read_only','content_editor','admin'),true))$profile='read_only';$settings=MGD_WordPress_MCP::get_settings();$settings['permission_profile']=$profile;$settings['writes_enabled']=in_array($profile,array('content_editor','admin'),true);$settings['divi_writes_enabled']=in_array($profile,array('content_editor','admin'),true);$settings['media_imports_enabled']=in_array($profile,array('content_editor','admin'),true);$settings['maintenance_enabled']='admin'===$profile;update_option(MGD_WordPress_MCP::OPTION_SETTINGS,$settings,false);wp_safe_redirect(admin_url('tools.php?page=mgd-wordpress-mcp&tab=wizard&profile_saved=1#mgd-security-profiles'));exit;}
 public function finish(){if(!current_user_can('manage_options'))wp_die(esc_html__('Keine Berechtigung.','mgd-wordpress-mcp'));check_admin_referer('mgd_wpmcp_wizard_finish');$d=self::data();$d['completed']=true;update_option(self::OPTION_WIZARD,$d,false);wp_safe_redirect(admin_url('tools.php?page=mgd-wordpress-mcp&tab=status'));exit;}
 private static function status_item($ok,$label,$detail=''){echo '<div class="mgd-wpmcp-ready-item '.($ok?'is-ok':'is-warn').'"><span class="mgd-wpmcp-ready-dot">'.($ok?'✓':'!').'</span><span><strong>'.esc_html($label).'</strong>';if($detail)echo '<small>'.esc_html($detail).'</small>';echo '</span></div>';}
 private static function profile_label($profile){$labels=array('read_only'=>'Nur lesen','content_editor'=>'Inhalte bearbeiten','admin'=>'Administration');return isset($labels[$profile])?$labels[$profile]:'Nur lesen';}
 private static function client_config($key){$configs=MGD_WordPress_MCP_Client_Config::configs();$map=array('claude_code'=>'claude-code','codex'=>'codex','cursor'=>'generic','generic'=>'generic');$source=isset($map[$key])?$map[$key]:'generic';return array('config'=>isset($configs[$source])?$configs[$source]:'','note'=>'Zugangsdaten nur im Secret-Speicher des Clients hinterlegen. Nicht im Plugin, Chat oder Repository speichern.');}
 public static function render(){
  $data=self::data();$detected=MGD_WordPress_MCP_Environment::builder();$locks=MGD_WordPress_MCP_Environment::frontend_locks();$doctor=MGD_WordPress_MCP_Doctor::summary();$profile=MGD_WordPress_MCP_Security::profile();$adapter=class_exists('\\WP\\MCP\\Core\\McpAdapter');
  ?>
  <div class="mgd-wpmcp-wizard-shell">
   <section class="mgd-wpmcp-card mgd-wpmcp-wizard-intro"><span class="mgd-wpmcp-step-kicker">SCHRITT FÜR SCHRITT</span><h2>WordPress mit deinem KI-Agenten verbinden</h2><p>MGD WordPress MCP prüft deine Website, legt fest was der Agent darf und erzeugt anschließend die passende Verbindung. Zugangsdaten werden nicht im Plugin gespeichert.</p></section>
   <section class="mgd-wpmcp-card"><div class="mgd-wpmcp-section-head"><span class="mgd-wpmcp-step">1</span><div><h2>Ist deine Website bereit?</h2><p>Die wichtigsten Voraussetzungen werden automatisch geprüft.</p></div></div><div class="mgd-wpmcp-ready-grid">
    <?php self::status_item(version_compare(get_bloginfo('version'),'6.9','>='),'WordPress '.get_bloginfo('version'),'Abilities API verfügbar');self::status_item(is_ssl(),'HTTPS',is_ssl()?'Sichere Verbindung aktiv':'Für Remote-MCP empfohlen');self::status_item($adapter,'MCP Adapter',$adapter?'Offizieller Adapter erkannt':'Noch nicht erkannt');self::status_item(true,$detected['label'],'Builder erkannt');self::status_item(!$locks['potentially_locked'],'Frontend-Zugriff',$locks['potentially_locked']?'Schutz erkannt, nur bei visueller Prüfung relevant':'Kein Schutz erkannt'); ?>
   </div><div class="mgd-wpmcp-doctor-summary"><strong>Connection Doctor:</strong> <?php echo esc_html($doctor['passed'].' von '.$doctor['total'].' Prüfungen erfolgreich'); ?> <a href="<?php echo esc_url(admin_url('tools.php?page=mgd-wordpress-mcp&tab=help'));?>">Details prüfen →</a></div></section>
   <section class="mgd-wpmcp-card"><div class="mgd-wpmcp-section-head"><span class="mgd-wpmcp-step">2</span><div><h2>Welcher Builder wird verwendet?</h2><p>Der Agent kann seine Arbeitsweise dadurch an deine Website anpassen.</p></div></div><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="mgd_wpmcp_wizard_save"><?php wp_nonce_field('mgd_wpmcp_wizard_save');$choices=array('divi'=>'Divi 5 / Divi Builder','elementor'=>'Elementor','gutenberg'=>'WordPress Block Editor / Gutenberg','bricks'=>'Bricks','beaver-builder'=>'Beaver Builder','other'=>'Anderes System');$selected=$data['builder']?$data['builder']:$detected['type'];?><div class="mgd-wpmcp-choice-grid"><?php foreach($choices as $value=>$label):?><label class="mgd-wpmcp-choice"><input type="radio" name="builder" value="<?php echo esc_attr($value);?>" <?php checked($selected,$value);?>><span><strong><?php echo esc_html($label);?></strong><?php if($value===$detected['type']):?><small>Automatisch erkannt</small><?php endif;?></span></label><?php endforeach;?></div><p><label>Anderes System<br><input class="regular-text" type="text" name="other_builder" value="<?php echo esc_attr($data['other_builder']);?>"></label></p><?php if('divi'===$selected||'divi'===$detected['type']):?><div class="mgd-wpmcp-recommend"><strong>Divi 5 erkannt</strong><p>Für Claude Code und Codex empfehlen wir zusätzlich den kostenlosen MGD Divi 5 Dev Skill. Er läuft beim Agenten und benötigt keine WordPress-Zugangsdaten.</p><label><input type="checkbox" name="divi_skill" value="1" <?php checked('recommended',$data['divi_skill']);?>> Divi 5 Dev Skill verwenden</label> <a target="_blank" rel="noopener" href="https://github.com/MichaelGahnDESIGN/MGD_Divi5-Dev_SKILL">Skill ansehen →</a></div><?php endif;?><?php submit_button('Builder speichern','secondary');?></form></section>
   <section id="mgd-security-profiles" class="mgd-wpmcp-card"><div class="mgd-wpmcp-section-head"><span class="mgd-wpmcp-step">3</span><div><h2>Was darf dein Agent?</h2><p>Wähle das Profil direkt hier. Die Auswahl wird sofort gespeichert.</p></div></div><div class="mgd-wpmcp-profile-grid"><?php $profiles=array('read_only'=>array('Nur lesen','Der sichere Start. Website analysieren und Inhalte lesen, aber nichts verändern.'),'content_editor'=>array('Inhalte bearbeiten','Beiträge, Seiten, Medien, SEO und freigegebene Builder-Funktionen bearbeiten.'),'admin'=>array('Administration','Zusätzlich Wartung und Updates. Kritische Aktionen benötigen weitere Bestätigungen.'));foreach($profiles as $key=>$p):?><form class="mgd-wpmcp-profile <?php echo $profile===$key?'is-active':'';?>" method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="mgd_wpmcp_wizard_profile"><input type="hidden" name="profile" value="<?php echo esc_attr($key);?>"><?php wp_nonce_field('mgd_wpmcp_wizard_profile');?><span class="mgd-wpmcp-profile-check"><?php echo $profile===$key?'✓':'○';?></span><strong><?php echo esc_html($p[0]);?></strong><small><?php echo esc_html($p[1]);?></small><button type="submit" class="button <?php echo $profile===$key?'':'button-secondary';?>" <?php disabled($profile,$key);?>><?php echo $profile===$key?'Aktiv':'Auswählen';?></button></form><?php endforeach;?></div><p class="description">Aktuell: <strong><?php echo esc_html(self::profile_label($profile));?></strong>. Unter „Sicherheit & Freigaben“ kannst du die automatisch gesetzten Einzelrechte später weiter anpassen.</p></section>
   <section class="mgd-wpmcp-card"><div class="mgd-wpmcp-section-head"><span class="mgd-wpmcp-step">4</span><div><h2>Zugang für deinen Agenten erstellen</h2><p>WordPress Application Passwords sind getrennte Zugangsschlüssel. Dein normales WordPress-Passwort wird nicht weitergegeben.</p></div></div><?php if($adapter):?><div class="mgd-wpmcp-success-box"><strong>✓ MCP Adapter ist bereits installiert und aktiv.</strong><span>Du musst ihn nicht erneut installieren.</span></div><?php else:?><div class="mgd-wpmcp-warning-box"><strong>MCP Adapter fehlt noch.</strong><a class="button" target="_blank" rel="noopener" href="https://github.com/WordPress/mcp-adapter/releases/latest">Adapter herunterladen</a></div><?php endif;?><div class="mgd-wpmcp-numbered"><div><b>1</b><span><strong>Application Password erstellen</strong><small>Am besten für einen eigenen WordPress-Benutzer mit möglichst wenigen Rechten.</small></span><a class="button button-primary" href="<?php echo esc_url(admin_url('profile.php#application-passwords-section'));?>">Zugang erstellen</a></div><div><b>2</b><span><strong>Endpoint verwenden</strong><small><?php echo esc_html(MGD_WordPress_MCP::adapter_endpoint_url());?></small></span></div><div><b>3</b><span><strong>Client konfigurieren</strong><small>Die passende Konfiguration erzeugen wir im nächsten Schritt.</small></span></div></div></section>
   <section class="mgd-wpmcp-card"><div class="mgd-wpmcp-section-head"><span class="mgd-wpmcp-step">5</span><div><h2>Womit möchtest du WordPress verbinden?</h2><p>Wähle deinen Client. Zugangsdaten werden absichtlich nicht in die Konfiguration geschrieben.</p></div></div><div class="mgd-wpmcp-client-grid"><?php foreach(array('claude_code'=>'Claude Code','codex'=>'Codex','cursor'=>'Cursor / VS Code','generic'=>'Anderer MCP Client') as $key=>$label):$cfg=self::client_config($key);?><details class="mgd-wpmcp-client"><summary><?php echo esc_html($label);?><span>Konfiguration anzeigen</span></summary><pre><code><?php echo esc_html($cfg['config']);?></code></pre><p><?php echo esc_html($cfg['note']);?></p></details><?php endforeach;?></div></section>
   <section class="mgd-wpmcp-card mgd-wpmcp-finish"><div><h2>Bereit für den Verbindungstest</h2><p>Öffne jetzt den Connection Doctor. Danach kannst du den Assistenten abschließen.</p></div><div><a class="button button-primary button-hero" href="<?php echo esc_url(admin_url('tools.php?page=mgd-wordpress-mcp&tab=help'));?>">Verbindung testen</a><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="mgd_wpmcp_wizard_finish"><?php wp_nonce_field('mgd_wpmcp_wizard_finish');?><button class="button" type="submit">Assistent abschließen</button></form></div></section>
  </div><?php
 }
}
